apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-cd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-cd
  template:
    metadata:
      labels:
        app: my-app-cd
    spec:
      containers:
      - name: my-app-cd
        image: ajanasokan/tried_so_hard:build_number_13
        ports:
        - containerPort: 80
