apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-cd
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-app-cd
  template:
    metadata:
      labels:
        app: my-app-cd
    spec:
      containers:
      - name: my-app-cd
        image: ajanasokan/akash_testt:build_number_16
        ports:
        - containerPort: 80
